network:
  version: 2
  renderer: networkd
  ethernets:
    mgbe0:
      dhcp4: false
      addresses:
        - 10.0.0.66/24
    mgbe1:
      dhcp4: false
      addresses:
        - 10.0.0.67/24
        